# Generated by Django 3.1.14 on 2022-07-10 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_intern', models.CharField(max_length=10)),
                ('ref_fourn', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=64)),
                ('pu', models.FloatField()),
                ('unite', models.CharField(default='P', max_length=10)),
                ('stock', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_demande', models.CharField(default='', max_length=64)),
                ('article_demande', models.CharField(default='', max_length=30)),
                ('fournisseur_demande', models.CharField(default='', max_length=64)),
                ('quantity_demande', models.IntegerField(default=0)),
                ('unity_demande', models.CharField(default='PIECE', max_length=10)),
                ('prix_demande', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimensionAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('type_achat', models.CharField(max_length=20)),
                ('is_aprouved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='List_item_on_Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_dem', models.CharField(max_length=64)),
                ('article_dem', models.CharField(max_length=30)),
                ('fournisseur_dem', models.CharField(max_length=64)),
                ('quantity_dem', models.IntegerField()),
                ('unity_dem', models.CharField(default='PIECE', max_length=10)),
                ('pu_dem', models.FloatField()),
                ('prix_dem', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_permission', models.BooleanField(default=False)),
                ('achat_permission', models.BooleanField(default=False)),
                ('magasin_permission', models.BooleanField(default=False)),
                ('production_permission', models.BooleanField(default=False)),
                ('maintenance_permission', models.BooleanField(default=False)),
                ('user_permission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List_item_on_Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=20)),
                ('article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.article')),
                ('fournisseur', models.ForeignKey(default='F', on_delete=django.db.models.deletion.CASCADE, to='home.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='founisseur',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.fournisseur'),
        ),
        migrations.AddField(
            model_name='article',
            name='projet',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='home.projet'),
        ),
    ]
