# Generated by Django 3.1.14 on 2022-07-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensionachat',
            name='is_aprouved',
        ),
        migrations.AddField(
            model_name='dimensionachat',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
