# Generated by Django 3.1.14 on 2022-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220710_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionachat',
            name='is_aprouved',
            field=models.BooleanField(default=False),
        ),
    ]
