# Generated by Django 3.1.14 on 2022-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dimensionachat_is_aprouved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprouvedAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('type_achat', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dimensionachat',
            name='is_aprouved',
        ),
    ]
