# Generated by Django 3.1.14 on 2022-07-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220710_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprouvedachat',
            old_name='data',
            new_name='date',
        ),
    ]
