# Generated by Django 3.1.14 on 2022-07-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220710_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprouvedachat',
            old_name='user',
            new_name='user_name',
        ),
    ]
