# Generated by Django 3.1.14 on 2022-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220710_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimensionachat',
            old_name='type_achat',
            new_name='type_achat_dim',
        ),
        migrations.RenameField(
            model_name='dimensionachat',
            old_name='user',
            new_name='user_dim',
        ),
    ]
