# Generated by Django 3.1.14 on 2022-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_demande_pu_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='identifier_demande',
            field=models.CharField(default='', max_length=64),
        ),
    ]
