# Generated by Django 3.1.14 on 2022-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220711_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='stock',
            new_name='stock_en_commande',
        ),
        migrations.AddField(
            model_name='article',
            name='stock_magasin',
            field=models.FloatField(default=0),
        ),
    ]
