# Generated by Django 3.1.14 on 2022-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220712_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_item_on_commande',
            name='article',
        ),
        migrations.RemoveField(
            model_name='list_item_on_commande',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='list_item_on_commande',
            name='quantity',
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='article_com',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='fournisseur_com',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='prix_com',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='pu_com',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='quantity_com',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='unity_com',
            field=models.CharField(default='PIECE', max_length=10),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='user_com',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='demande',
            name='article_demande',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='list_item_on_demande',
            name='quantity_dem',
            field=models.FloatField(),
        ),
    ]
