# Generated by Django 3.1.14 on 2022-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220712_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='prix_comande',
            new_name='prix_commande',
        ),
    ]
