# Generated by Django 3.1.14 on 2022-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220712_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprouvedachat',
            name='identifier',
            field=models.CharField(default='', max_length=64),
        ),
    ]
