# Generated by Django 3.1.14 on 2022-07-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_bc_fournisseur_identifier_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='article_commande',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='fournisseur_commande',
            new_name='fournisseur',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='numero_commande',
            new_name='numero_bc',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='prix_commande',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='prix_total_commande',
            new_name='prix_total',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='pu_commande',
            new_name='pu',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='quantity_commande',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='ref_fourn_commande',
            new_name='ref_fourn',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='ref_stgi_commande',
            new_name='ref_stgi',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='rmq_commande',
            new_name='rmq',
        ),
        migrations.RenameField(
            model_name='bc_fournisseur',
            old_name='unity_commande',
            new_name='unity',
        ),
    ]
