# Generated by Django 3.1.14 on 2022-07-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220718_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='article',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='pu',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='ref_fourn',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='ref_stgi',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='unity',
        ),
    ]
