# Generated by Django 3.1.14 on 2022-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_commande_is_approuved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(default='', max_length=64)),
                ('chez_fournisseur', models.BooleanField(default=0)),
                ('livrer_fournisseur', models.BooleanField(default=0)),
                ('arriver_chez_gts', models.BooleanField(default=0)),
                ('en_transit', models.BooleanField(default=0)),
                ('livraison_stgi', models.BooleanField(default=0)),
                ('etat_commande', models.BooleanField(default=1)),
            ],
        ),
    ]
