# Generated by Django 3.1.14 on 2022-07-23 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_suivicommande_nom_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicommande',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
