# Generated by Django 3.1.14 on 2022-07-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20220723_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandedAchat',
        ),
        migrations.AddField(
            model_name='demande',
            name='etat_demande',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='suivicommande',
            name='etat_paiement',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='suivicommande',
            name='is_confirmed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='suivicommande',
            name='numero_facture',
            field=models.CharField(default='', max_length=64),
        ),
    ]
