# Generated by Django 3.1.14 on 2022-07-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20220723_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(default='', max_length=64)),
                ('numero_commande', models.CharField(default='', max_length=64)),
                ('date_envoyee', models.DateTimeField(auto_now_add=True)),
                ('remarque', models.CharField(default='', max_length=300)),
                ('date_souhaitee', models.DateField()),
                ('is_confirmed', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='suivicommande',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='suivicommande',
            name='etat_commande',
            field=models.CharField(default='', max_length=64),
        ),
    ]
