# Generated by Django 3.1.14 on 2022-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20220723_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeachat',
            name='date_souhaitee',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
