# Generated by Django 3.1.14 on 2022-07-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220727_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeachat',
            name='date_envoyee',
        ),
    ]
