# Generated by Django 3.1.14 on 2022-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_commandetosend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandeToSend',
        ),
        migrations.AddField(
            model_name='commande',
            name='is_confirmed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='is_sent',
            field=models.BooleanField(default=0),
        ),
    ]
