# Generated by Django 3.1.14 on 2022-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_commandeachat_date_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeachat',
            name='is_confirmed',
            field=models.CharField(default='NON', max_length=10),
        ),
    ]
