# Generated by Django 3.1.14 on 2022-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20220731_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='is_confirmed',
            field=models.CharField(default='NON', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='is_confirmed',
            field=models.BooleanField(default=0),
        ),
    ]
