# Generated by Django 3.1.14 on 2022-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20220731_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bc_fournisseur',
            name='ref_bateaux',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bc_fournisseur',
            name='remarque',
            field=models.CharField(default='', max_length=300),
        ),
    ]
