# Generated by Django 3.1.14 on 2022-08-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20220801_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='date_livraison_sht',
        ),
    ]
