# Generated by Django 3.1.14 on 2022-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220802_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_ready',
            field=models.BooleanField(default=0),
        ),
    ]
