# Generated by Django 3.1.14 on 2022-08-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_suivicommande_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicommande',
            name='move',
            field=models.IntegerField(default=400),
        ),
    ]
