# Generated by Django 3.2.11 on 2022-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_suivicommande_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_approuved',
            field=models.BooleanField(default=0),
        ),
    ]
