# Generated by Django 3.2.11 on 2022-08-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_demande_is_approuved'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeachat',
            name='email_fournisseur',
            field=models.CharField(default='', max_length=64),
        ),
    ]
