# Generated by Django 3.2.11 on 2022-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_demande_is_approuved'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantity_receptionnee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantity_restante',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='email_fournisseur',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='is_planified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='list_item_on_commande',
            name='ref_com',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='bc_fournisseur',
            name='date_livraison_sht',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='list_item_on_commande',
            name='unity_com',
            field=models.CharField(default='P', max_length=10),
        ),
    ]
