# Generated by Django 3.1.14 on 2022-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_suivicommande_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='type',
            field=models.CharField(default='DIRECT', max_length=64),
        ),
    ]
