# Generated by Django 3.2.11 on 2022-09-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_commande_is_refused'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefusedAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('type_achat', models.CharField(max_length=64)),
                ('identifier', models.CharField(default='', max_length=64)),
                ('fournisseur', models.CharField(default='', max_length=64)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
