# Generated by Django 3.2.11 on 2022-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_commande_motif_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeachat',
            name='type',
            field=models.CharField(default='LOCAL', max_length=64),
        ),
    ]
