# Generated by Django 3.2.11 on 2022-09-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_sortiedirecte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortiedirecte',
            name='ref_intern',
        ),
    ]
