# Generated by Django 3.2.11 on 2022-09-15 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_sortiedirecte_ref_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiedirecte',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortiedirecte',
            name='user_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
