# Generated by Django 3.2.11 on 2022-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20220915_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=64)),
                ('fonction', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='sortiedirecte',
            name='operateur',
            field=models.CharField(default='', max_length=64),
        ),
    ]
