# Generated by Django 3.2.11 on 2022-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20220916_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='matricule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operateur',
            name='site',
            field=models.CharField(default='Composite', max_length=64),
        ),
    ]
