# Generated by Django 3.2.11 on 2022-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20220916_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionachat',
            name='fournisseur_dim',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dimensionachat',
            name='projet_dim',
            field=models.CharField(default='', max_length=64),
        ),
    ]
