# Generated by Django 3.2.11 on 2022-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20220926_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='projet',
            field=models.CharField(default='', max_length=64),
        ),
    ]
