# Generated by Django 3.2.11 on 2022-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_commande_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='ref_fourn_commande',
            field=models.CharField(default='', max_length=64),
        ),
    ]
