# Generated by Django 3.2.11 on 2022-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_commande_ref_fourn_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprouvedachat',
            name='projet',
            field=models.CharField(default='', max_length=64),
        ),
    ]
