# Generated by Django 3.2.11 on 2022-10-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_aprouvedachat_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_bc', models.CharField(default='TOUS PROJETS', max_length=64)),
                ('dls_bc', models.DateField()),
                ('fournisseur_bc', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
