# Generated by Django 3.2.11 on 2022-10-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_bc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bc',
            name='dls_bc',
            field=models.DateTimeField(),
        ),
    ]
