# Generated by Django 3.2.11 on 2022-10-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_bc_dls_bc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bc',
            name='num_bc',
            field=models.IntegerField(default=100),
        ),
    ]
