# Generated by Django 3.2.11 on 2022-10-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_bc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bc',
            name='num_bc',
            field=models.CharField(default='', max_length=64),
        ),
    ]
