# Generated by Django 3.2.11 on 2022-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_bc_num_bc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionachat',
            name='dls_dim',
            field=models.DateTimeField(default='2022-12-12'),
        ),
    ]
