# Generated by Django 3.2.11 on 2022-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_dimensionachat_dls_dim'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionachat',
            name='numero_dim',
            field=models.CharField(default='', max_length=64),
        ),
    ]
