# Generated by Django 3.2.11 on 2022-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_dimensionachat_numero_dim'),
    ]

    operations = [
        migrations.AddField(
            model_name='refusedachat',
            name='numero',
            field=models.CharField(default='', max_length=64),
        ),
    ]
