# Generated by Django 3.2.11 on 2022-10-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_refusedachat_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionachat',
            name='is_recalled',
            field=models.BooleanField(default=0),
        ),
    ]
