# Generated by Django 3.2.11 on 2022-10-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20221010_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='bc',
            name='is_send_approval',
            field=models.BooleanField(default=0),
        ),
    ]
