# Generated by Django 3.2.11 on 2022-10-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_bc_is_send_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandeachat',
            old_name='remarque',
            new_name='ref_projet',
        ),
    ]
