# Generated by Django 3.2.11 on 2022-10-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_rename_remarque_commandeachat_ref_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='date_livraison_sht',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='numero_bc',
        ),
        migrations.RemoveField(
            model_name='bc_fournisseur',
            name='ref_bateaux',
        ),
    ]
