# Generated by Django 3.2.11 on 2022-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20221011_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprouvedachat',
            name='dls',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
