# Generated by Django 3.2.11 on 2022-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_aprouvedachat_dls'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprouvedachat',
            name='is_ready',
            field=models.BooleanField(default=0),
        ),
    ]
